# Generated by Django 5.0.1 on 2024-09-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discout',
            new_name='discount',
        ),
    ]
